graph LR
    accTitle: 描画パス構想図
    accDescr: 描画パスの構想をまとめて見やすく、想像しやすくしたもの
    
    subgraph USePass[パス描画]
        direction TD
        subgraph Begin ["Begin()"]
            SetTarget["RenderTarges設定"]
            B@{ shape: braces, label: "OMSetRenderTargetsのみ" }
            SetDrawState["DrawState設定"]
        end

        
        subgraph ExecuteCommands [描画コマンド配列実行]
            C["ResouceBarrier遷移を<br>ここで行う"]
            D["RenderTargetのClearも<br>ここで行う"]
            E["DrawCallもここで行う"]
        end

        subgraph　End ["End()"]
            F@{ shape: braces, label: "実装するか不明<br>するならここで最後のBarrier遷移" }
        end
    end

    Begin --> ExecuteCommands
    ExecuteCommands --> End