flowchart TD
    Start(プログラム作成) --> EntryApp([Applicaiton開始])
    EntryApp --> initialize_App{Application作成}
    initialize_App -- 作成成功 --> run_App{Applicaiton実行}
    initialize_App -- 作成失敗 --> End(プログラム終了)
    run_App -- Applicaiton終了 --> End
    end